### ISSUE TITLE
Falta la licencia

### ISSUE THREAD

**Issue by Delawen** [jsegu/greennessr#1]
No veo bajo qué licencia está publicado. ¿Podríais añadirla en un lugar visible?

**Comment by jsegu** [comment]
Listo! Muchas gracias por tu comentario :)

**Comment by Delawen** [comment]
Gracias :)

**Comment by Delawen** [comment]
Uh, oh, cerré pronto. ¿Entonces es software libre pero bajo qué licencia? GPL, MIT, BSD,... ¿Dominio público? Si no pones una explícitamente no se puede asumir que sea software libre. Por defecto la licencia es restrictiva.

https://choosealicense.com/licenses/

**Comment by jsegu** [comment]
Ahora creo que si.
Disculpa, soy nuevo en todo esto y a veces con estos temas me pierdo un poco. 
Gracias

**Comment by Delawen** [comment]
Nada que disculpar. ¡Y gracias por compartir!
